apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testproj
  namespace: argocd
spec:
  project: default
  source:
    chart: testproj
    repoURL: https://infa-hbalakrishnan.github.io/argo-test-proj/
    targetRevision: 0.1.4
    helm:
      releaseName: testproj
  destination:
    server: "https://kubernetes.default.svc"
    namespace: testproj